export default {
  'AChroMap': require('./../../static/tools_logo/achromap.png'),
  'Adaptation Browser': require('./../../static/tools_logo/adaptationbrowser.png'),
  'Breast Cancer Browser': require('./../../static/tools_logo/breastcancerbrowser.jpg'),
  'Cell Dynamics Browser': require('./../../static/tools_logo/celldynamicsbrowser.png'),
  'CMap Query': require('./../../static/tools_logo/cmapquery.png'),
  'CREEDS': require('./../../static/tools_logo/creeds.png'),
  'Drug Response Browser': require('./../../static/tools_logo/drugresponsebrowser.jpg'),
  'Drug-Pathway Browser': require('./../../static/tools_logo/drugpathwaybrowser.jpg'),
  'Drug/Cell-line Browser': require('./../../static/tools_logo/drug_celllinebrowser.png'),
  'DToxS Portal': require('./../../static/tools_logo/dtoxportal.png'),
  'Enrichr': require('./../../static/tools_logo/enrichr.png'),
  'GEN3VA': require('./../../static/tools_logo/gen3va.png'),
  'GEO2Enrichr': require('./../../static/tools_logo/geo2enrichr.png'),
  'GF Response Browser': require('./../../static/tools_logo/gfresponsebrowser.jpg'),
  'GR Browser': require('./../../static/tools_logo/grbrowser.png'),
  'GUIdock': require('./../../static/tools_logo/guidock.png'),
  'Harmonizome': require('./../../static/tools_logo/harmonizome.png'),
  'HMS LINCS Database': require('./../../static/tools_logo/hmslincsdatabase.png'),
  'iLINCS': require('./../../static/tools_logo/ilincs.png'),
  'ImageRail': require('./../../static/tools_logo/imagerail.png'),
  'L1000CDS2': require('./../../static/tools_logo/l1000cds2.png'),
  'LINCS Canvas Browser': require('./../../static/tools_logo/lincscanvasbrowser.png'),
  'LINCS Data Explorer': require('./../../static/tools_logo/lincsdataexplorer.png'),
  'LINCS Data Portal': require('./../../static/tools_logo/lincsdataportal.png'),
  'CLUE Platform': require('./../../static/tools_logo/lincscloudapps.jpg'),
  'MEPmosaic': require('./../../static/tools_logo/mepmosaic.png'),
  'Network2Canvas': require('./../../static/tools_logo/network2canvas.png'),
  'OMERO': require('./../../static/tools_logo/omero.jpg'),
  'Omics Integrator': require('./../../static/tools_logo/omicsintegrator.png'),
  'PAEA': require('./../../static/tools_logo/paea.png'),
  'Panorama': require('./../../static/tools_logo/panorama.png'),
  'Phosphosite Plus': require('./../../static/tools_logo/phosphositeplus.png'),
  'piLINCS': require('./../../static/tools_logo/pilincs.png'),
  'PIUMet': require('./../../static/tools_logo/piumet.jpg'),
  'RTK Profile Browser': require('./../../static/tools_logo/rtkprofilebrowser.jpg'),
  'SEP L1000': require('./../../static/tools_logo/sepl1000.png'),
  'Slicr': require('./../../static/tools_logo/slicr.png'),
  'TieDIE': require('./../../static/tools_logo/tiedie.jpg'),
  'Touchstone': require('./../../static/tools_logo/touchstone.png'),
  'LINCS Project Mobile': require('./../../static/tools_logo/iphone_tools_mockup.png'),
  'Touchstone': require('./../../static/tools_logo/touchstone.png'),
  'Morpheus': require('./../../static/tools_logo/morpheus.png'),
  'Repurposing App': require('./../../static/tools_logo/repurposing.png'),
  'ICV App': require('./../../static/tools_logo/icv.png'),
};
